export const commandResponses = {
  about: [
    "Hi, I'm Rishabh Mishra!",
    "I'm a Software Engineer who likes to build stuff.",
    'I have 3 years of experience in Software Development.',
    'Type "skills" to see my technical expertise.',
  ],
  email: ['mail@rishmi5h.com'],
  projects: [
    'My Notable Projects:',
    '1. Imagery',
    '   Description: A platform for all your image management needs.',
    '   Features: Authentication, Upload, Retrieve, Transform and Edit images.',
    '   Technologies: React, Spring Boot, MySQL, AWS S3, Tailwind CSS, TypeScript',
    '   Link: https://imagery.rishmi5h.com',
    '',
    '2. Scalable E-Commerce',
    '   Description: A fully functional e-commerce website with a scalable architecture.',
    '   Features: Authentication, Product Management, Order Processing, Notification System.',
    '   Technologies: Spring Boot, React, MySQL, MongoDB, Keycloak, Kafka, Kubernetes, Prometheus, Grafana, Wiremock',
    '   Link: https://github.com/rishmi5h/ecommerce',
    '',
    'Type "socials" to see my social media profiles for more information.',
  ],
  skills: [
    'My Technical Skills:',
    '- Programming Languages: Java, JavaScript, TypeScript, Python, SQL',
    '- Frameworks & Libraries: Spring Boot, React, Next.js, Tailwind CSS, Node.js',
    '- Tools: Git, Docker, Kubernetes, Jenkins, Airflow, AWS',
    '- Other: Kafka, Oracle DB, PostgreSQL, Redis',
    'Type "projects" to see my projects.',
  ],
  welcome: [
    'Welcome to My Terminal Portfolio!',
    'Type "help" to see available commands.',
    '',
  ],
};
